version: '3.1'
services:
  parser:
    image: alphabotsystem/alpha-parser
    build:
      context: ./
      dockerfile: ./services/parser/build/dockerfile
    volumes:
     - ./services/parser:/usr/src/parser
     - ./libraries:/usr/src/parser/libraries
    ports:
     - "6900:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key

  database:
    image: alphabotsystem/alpha-database
    build:
      context: ./
      dockerfile: ./services/database/build/dockerfile
    volumes:
     - ./services/database:/usr/src/database
     - ./libraries:/usr/src/database/libraries
    ports:
     - "6901:6900"
    secrets:
     - source: google-cloud-auth
       target: google-cloud-auth/key

  image-server:
    image: alphabotsystem/alpha-image-server
    build:
      context: ./
      dockerfile: ./services/images/build/dockerfile
    volumes:
     - ./services/images:/usr/src/image-server
     - ./libraries:/usr/src/image-server/libraries
    ports:
     - "6902:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser

  quote-server:
    image: alphabotsystem/alpha-quote-server
    build:
      context: ./
      dockerfile: ./services/quotes/build/dockerfile
    volumes:
     - ./services/quotes:/usr/src/quote-server
     - ./libraries:/usr/src/quote-server/libraries
    ports:
     - "6903:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser

  detail-server:
    image: alphabotsystem/alpha-detail-server
    build:
      context: ./
      dockerfile: ./services/details/build/dockerfile
    volumes:
     - ./services/details:/usr/src/detail-server
     - ./libraries:/usr/src/detail-server/libraries
    ports:
     - "6904:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser

  candle-server:
    image: alphabotsystem/alpha-candle-server
    build:
      context: ./
      dockerfile: ./services/candles/build/dockerfile
    volumes:
     - ./services/candles:/usr/src/candle-server
     - ./libraries:/usr/src/candle-server/libraries
    ports:
     - "6905:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser

  trade-server:
    image: alphabotsystem/alpha-trade-server
    build:
      context: ./
      dockerfile: ./services/trades/build/dockerfile
    volumes:
     - ./services/trades:/usr/src/trade-server
     - ./libraries:/usr/src/trade-server/libraries
    ports:
     - "6906:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: api-keys-decryption-key
       target: api-keys-decryption/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser
     - database

  cron-jobs:
    image: alphabotsystem/alpha-cron-jobs
    build:
      context: ./
      dockerfile: ./services/jobs/build/dockerfile
    volumes:
      - ./services/jobs:/usr/src/cron-jobs
      - ./libraries:/usr/src/cron-jobs/libraries
    ports:
     - "6907:6900"
    secrets:
      - source: alpha-service-keys
        target: alpha-service/key
      - source: google-cloud-auth
        target: google-cloud-auth/key
    depends_on:
     - parser
     - database
     - candle-server
     - trade-server

  discord-bot:
    image: alphabotsystem/alpha-discord-bot
    build:
      context: ./
      dockerfile: ./bots/discord/build/dockerfile
    volumes:
     - ./bots/discord:/usr/src/discord-bot
     - ./libraries:/usr/src/discord-bot/libraries
    ports:
     - "6910:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser
     - database
     - image-server
     - quote-server
     - detail-server
     - candle-server
     - trade-server

  satellites:
    image: alphabotsystem/alpha-satellites
    build:
      context: ./
      dockerfile: ./bots/satellites/build/dockerfile
    volumes:
      - ./bots/satellites:/usr/src/satellites
      - ./libraries:/usr/src/satellites/libraries
    ports:
      - "6911:6900"
    secrets:
      - source: alpha-service-keys
        target: alpha-service/key
      - source: alpha-satellite-keys
        target: alpha-satellites/key
      - source: google-cloud-auth
        target: google-cloud-auth/key
    depends_on:
     - parser
     - database
     - quote-server

  twitter-bot:
    image: alphabotsystem/alpha-twitter-bot
    build:
      context: ./
      dockerfile: ./bots/twitter/build/dockerfile
    volumes:
     - ./bots/twitter:/usr/src/twitter-bot
     - ./libraries:/usr/src/twitter-bot/libraries
    ports:
     - "6912:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser
     - database
     - image-server
     - quote-server
     - detail-server
     - candle-server
     - trade-server

  discord-manager:
    image: alphabotsystem/alpha-discord-manager
    build:
      context: ./
      dockerfile: ./bots/manager/build/dockerfile
    volumes:
      - ./bots/manager:/usr/src/discord-manager
      - ./libraries:/usr/src/discord-manager/libraries
    secrets:
      - source: alpha-service-keys
        target: alpha-service/key
      - source: google-cloud-auth
        target: google-cloud-auth/key
    depends_on:
     - database


secrets:
  alpha-service-keys:
    file: ./keys/credentials
  api-keys-decryption-key:
    file: ./keys/api_keys_decryption_key
  alpha-satellite-keys:
    file: ./keys/satellites
  google-cloud-auth:
    file: ./keys/gcloud_credentials.json